#!/bin/bash

set -e

ghc-pkg unregister rematch
ghc-pkg unregister quickcheck-rematch
ghc-pkg unregister hunit-rematch
ghc-pkg unregister rematch-text

(cd core && cabal install)
(cd hunit-rematch && cabal install)
(cd text-rematch && cabal install)
(cd quickcheck-rematch && cabal install)
script/test
